### ISSUE TITLE
Did this work?

### ISSUE THREAD

**Issue by Foggalong** [ploctaux/com.numix.icons#1]
Curious if you ever got anywhere with developing this? Now that [Numix Core](https://github.com/numixproject/numix-core) is a thing this is potentially something that would be easier to do

**Comment by ploctaux** [comment]
oh boy, i never knew that was a thing...
well the thing is that this icon pack was never made, since you never gave me any working icon (lol) and i don't have a jailbreak anymore... so i can't do anything...

iirc pinbadge's one works-ish (looks like it does): https://github.com/Pinbadge/pinbadge-ios-theme

**Comment by Foggalong** [comment]
Oh okay, never mind then :)
